#!/usr/bin/env python
"""Where does injected knowledge live? (exp14 partition ablation)

Two normalizations, because they answer different questions and disagree:

  bits / M constrained weights -- how good is this SUBSTRATE, i.e. how much
      does the dequantization gap of these matrices hold? Favors partitions
      with few weights.
  bits / M trainable params    -- how good is this partition under a fixed
      low-rank BUDGET, which is what an implementer actually spends. This is
      the fair comparison for QIL-LoRA and the one we report.

A third column prices the damage: bits absorbed per unit of cross-domain
perplexity given up. A partition that absorbs less but breaks less can be
the better place to write.
"""

import json
from pathlib import Path

# Qwen3-1.7B-Base: 28 layers, hidden 2048, intermediate 6144,
# 16 query heads and 8 kv heads of dim 128.
H, I, L, RANK = 2048, 6144, 28, 64
SHAPES = {  # (out, in)
    "q_proj": (16 * 128, H), "k_proj": (8 * 128, H), "v_proj": (8 * 128, H),
    "o_proj": (H, 16 * 128), "gate_proj": (I, H), "up_proj": (I, H),
    "down_proj": (H, I),
}
ATTN_K = ("q_proj", "k_proj", "v_proj", "o_proj")
MLP_K = ("gate_proj", "up_proj", "down_proj")


def dense(keys, layers):
    return sum(SHAPES[k][0] * SHAPES[k][1] for k in keys) * layers


def lowrank(keys, layers):
    return sum(RANK * (SHAPES[k][0] + SHAPES[k][1]) for k in keys) * layers


RUNS = {
    "attention (all layers)":   ("exp14_attn", ATTN_K, L),
    "MLP (all layers)":         ("exp14_mlp", MLP_K, L),
    "gate+up (all layers)":     ("exp14_gateup", ("gate_proj", "up_proj"), L),
    "down_proj (all layers)":   ("exp14_down", ("down_proj",), L),
    "MLP layers 0-8":           ("exp14_early", MLP_K, 9),
    "MLP layers 9-18":          ("exp14_mid", MLP_K, 10),
    "MLP layers 19-27":         ("exp14_late", MLP_K, 9),
}
BITS, N = 11.9, 1000

rows = []
for label, (stem, keys, layers) in RUNS.items():
    p = Path(f"results/{stem}.json")
    if not p.exists():
        continue
    d = json.loads(p.read_text())
    rec = d["recall"]["merged"]
    lam = (d.get("ppl_lambada") or {}).get("merged")
    # CRITICAL: each partition run quantizes only its own matrices -- the rest
    # of the model stays at original fp32 -- so every run has a DIFFERENT
    # anchor. Pricing them all against the fully-quantized model's anchor
    # (28.67) makes the small partitions look free when they are not.
    anchor = (d.get("ppl_lambada") or {}).get("anchor_fp32")
    bits = rec * N * BITS
    dmg = (lam - anchor) if (lam and anchor) else None
    rows.append(dict(
        label=label, dense=dense(keys, layers), train=lowrank(keys, layers),
        rec=rec, wiki=d["ppl"]["merged"], lam=lam, anchor=anchor, dmg=dmg,
        bits=bits, sat=(d.get("merge") or {}).get("saturation"),
        per_dense=bits / dense(keys, layers) * 1e6,
        per_train=bits / lowrank(keys, layers) * 1e6,
        per_dmg=(bits / dmg if dmg and dmg > 0 else None),
    ))

rows.sort(key=lambda r: -r["per_train"])
print(f"{'partition':22} {'trainable':>11} {'recall':>7} {'anchor':>7} "
      f"{'LAMBADA':>8} {'dmg':>6} {'sat':>6} {'b/Mtrain':>9} {'bits/pt':>8}")
print("-" * 96)
for r in rows:
    lam = f"{r['lam']:8.2f}" if r["lam"] else "       -"
    anc = f"{r['anchor']:7.2f}" if r["anchor"] else "      -"
    dmg = f"{r['dmg']:+6.2f}" if r["dmg"] is not None else "     -"
    eff = f"{r['per_dmg']:8.0f}" if r["per_dmg"] else "       -"
    sat = f"{r['sat']:6.1%}" if r["sat"] is not None else "     -"
    print(f"{r['label']:22} {r['train']:11,} {r['rec']:7.1%} {anc} {lam} "
          f"{dmg} {sat} {r['per_train']:9.0f} {eff}")

print("\nEach row is priced against ITS OWN anchor: a partition run quantizes")
print("only its own matrices, so the seven runs do not share a baseline.")
print("b/Mtrain = probed bits absorbed per million trainable params")
print("bits/pt  = probed bits absorbed per point of LAMBADA given up")

def latex_table(rows):
    """Emit the same numbers as LaTeX so the paper cannot drift from the
    script -- it already had, by one unit in three cells."""
    out = ["% GENERATED by scripts/analyze_where.py -- do not edit by hand",
           "\\begin{tabular}{lrrrrrr}", "\\toprule",
           "partition & trainable & recall & own anchor & LAMBADA & "
           "bits/M$_{\\text{train}}$ & bits/pt \\\\", "\\midrule"]
    for r in rows:
        best = r["per_train"] == max(x["per_train"] for x in rows)
        bd = r["per_dmg"] and r["per_dmg"] == max(
            x["per_dmg"] or 0 for x in rows)
        bt = f"\\textbf{{{r['per_train']:.0f}}}" if best else f"{r['per_train']:.0f}"
        bg = (f"\\textbf{{{r['per_dmg']:.0f}}}" if bd
              else (f"{r['per_dmg']:.0f}" if r["per_dmg"] else "---"))
        out.append(
            f"{r['label'].replace('_', chr(92)+'_')} & {r['train']/1e6:.1f}M & "
            f"{r['rec']*100:.1f}\\% & {r['anchor']:.2f} & {r['lam']:.2f} & "
            f"{bt} & {bg} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out)


import sys as _sys
if "--write" in _sys.argv:
    Path("paper/tables/where.tex").write_text(latex_table(rows) + "\n")
    print("wrote paper/tables/where.tex")
