#!/usr/bin/env python
"""Generate the paper's result tables from the archived JSONs.

Typed tables drift: an earlier draft quoted a capacity exponent its own
figure did not produce, and mixed rehearsal fractions inside one comparison.
Everything downstream of this script is therefore computed, and every cell
carries the seed count it was averaged over.

  python scripts/make_tables.py            # print LaTeX
  python scripts/make_tables.py --write     # write paper/tables/*.tex
"""

from __future__ import annotations

import argparse
import json
import sys
import statistics as st
from pathlib import Path

R = Path("results")
BITS_PER_FACT = 11.9  # probed attributes only (city, job, company)

# row label -> (files, which stage to read)
#   'merged' = after clip-merge / after the bounded fill is materialized
#   'heal'   = after projected dense healing (or, for dense-only runs, the
#              projected dense training itself)
ROWS = [
    ("A: clip-merge", "projected",
     ["exp1c_replay10_qwen3-1.7b_r16_e24", "exp1c_s1", "exp1c_s2"], "merged"),
    ("CellFill $r{=}16$", "structural",
     ["exp16_qil_r16_replay10", "exp31_qil_r16_s1", "exp31_qil_r16_s2"],
     "merged"),
    ("A+: clip-merge $\\to$ heal", "projected",
     ["exp1c_replay10_qwen3-1.7b_r16_e24", "exp1c_s1", "exp1c_s2"], "heal"),
    ("CellFill $r{=}64$", "structural",
     ["exp10_qil_r64_qwen3-1.7b", "exp30_qil_r64_s1", "exp30_qil_r64_s2"],
     "merged"),
    ("B: projected dense", "projected",
     ["exp18_b_replay10_s0", "exp18_b_replay10_s1"], "heal"),
    ("B: projected dense", "projected",
     ["exp3_dense_qwen3-1.7b_e24", "exp3_s1", "exp3_s2"], "heal"),
    ("unconstrained dense", "none",
     ["exp4_free_qwen3-1.7b_e24", "exp4_free_s1", "exp4_free_s2"], "heal"),
]


def load(stem):
    p = R / f"{stem}.json"
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text())
    except json.JSONDecodeError:
        # a truncated archive is a defect to surface, not one to crash on
        print(f"[warn] {p.name} is not readable JSON; treated as absent")
        return None


def cell(d, stage, field):
    """field in {recall, wiki, lam}; returns None when absent."""
    if d is None:
        return None
    if stage == "heal":
        h = d.get("heal") or {}
        return {"recall": h.get("recall"), "wiki": h.get("ppl"),
                "lam": h.get("ppl_x")}[field]
    return {"recall": d["recall"].get("merged"),
            "wiki": d["ppl"].get("merged"),
            "lam": (d.get("ppl_lambada") or {}).get("merged")}[field]


def agg(vals):
    vals = [v for v in vals if v is not None]
    if not vals:
        return None, None, 0
    if len(vals) == 1:
        return vals[0], None, 1
    return st.mean(vals), st.stdev(vals), len(vals)


def fmt(mean, sd, n, pct=False, nd=2):
    if mean is None:
        return "---"
    scale = 100 if pct else 1
    unit = "\\%" if pct else ""
    if sd is None:
        return f"{mean * scale:.{nd}f}{unit}"
    return f"${mean * scale:.{nd}f}\\!\\pm\\!{sd * scale:.{nd}f}${unit}"


def violations(stems):
    tot = 0
    for s in stems:
        d = load(s)
        if d and (d.get("heal") or {}).get("invariance_violations"):
            tot += d["heal"]["invariance_violations"]
    return tot


def frontier_table():
    anchor = load("exp1c_s1")
    a_wiki = anchor["ppl"]["anchor_fp32"]
    a_lam = (anchor.get("ppl_lambada") or {}).get("anchor_fp32")
    o_wiki = anchor["ppl"]["original_fp32"]
    o_lam = (anchor.get("ppl_lambada") or {}).get("original_fp32")

    out = [
        "% GENERATED by scripts/make_tables.py -- do not edit by hand",
        "\\begin{tabular}{llccccrc}",
        "\\toprule",
        "method & invariance & reh. & recall & WikiText-2 & LAMBADA ppl$\\downarrow$ &"
        "bits/pt & seeds \\\\",
        "\\midrule",
        f"4-bit anchor & (reference) & --- & --- & {a_wiki:.2f} & "
        f"{a_lam:.2f} & --- & --- \\\\",
        f"original fp32 & (reference) & --- & --- & {o_wiki:.2f} & "
        f"{o_lam:.2f} & --- & --- \\\\",
        "\\midrule",
    ]
    for label, inv, stems, stage in ROWS:
        ds = [load(s) for s in stems]
        rs = [cell(d, stage, "recall") for d in ds]
        lams = [cell(d, stage, "lam") for d in ds]
        r = agg(rs)
        w = agg([cell(d, stage, "wiki") for d in ds])
        lam = agg(lams)
        inv_s = {"structural": "\\checkmark\\ (structural)",
                 "projected": "\\checkmark", "none": "$\\times$"}[inv]
        seeds = f"{r[2]}" + (f"/{lam[2]}" if lam[2] != r[2] else "")
        # Knowledge bought per point of cross-domain perplexity given up.
        # Computed PER SEED and averaged: the prose and the ledger quote
        # mean +/- std over seed-wise ratios (918+/-183, 1126+/-205, ...),
        # and a ratio of means is a different estimator that disagreed with
        # them by up to 4% in the same table.
        effs = [ri * 1000 * BITS_PER_FACT / (li - a_lam)
                for ri, li in zip(rs, lams)
                if ri is not None and li is not None and li > a_lam]
        eff = "---"
        if effs:
            em, es, en = agg(effs)
            eff = (f"${em:.0f}\\!\\pm\\!{es:.0f}$" if en > 1
                   else f"{em:.0f}")
        reh = {str((d.get("config") or {}).get("replay_frac"))
               for d in ds if d}
        reh_s = "/".join(sorted(reh)) if reh else "---"
        out.append(
            f"{label} & {inv_s} & {reh_s} & {fmt(*r, pct=True, nd=1)} & "
            f"{fmt(*w)} & {fmt(*lam)} & {eff} & {seeds} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out)


def config_table():
    keys = [("model", "base model"), ("n_facts", "facts"),
            ("epochs", "epochs"), ("rank", "LoRA rank"),
            ("lr", "learning rate"), ("bs", "batch size"),
            ("replay_frac", "fresh rehearsal fraction"),
            ("margin", "cell margin"), ("radius", "radius $\\rho$"),
            ("heal_epochs", "healing epochs"), ("heal_lr", "healing lr"),
            ("tanh_scale", "CellFill gain $s$")]
    seen: dict[str, set] = {k: set() for k, _ in keys}
    # results/ also holds runs belonging to other manuscripts. Restricting this
    # sweep to the manifest's curated list was tried and is worse: the manifest
    # omits the capacity sweeps, so the table then under-reports knobs the
    # paper does discuss. Instead the families that belong to other papers are
    # named and excluded, so this table stays a description of the range THIS
    # paper explored rather than of everything the repository has ever run.
    OTHER_PAPERS = ("exp48_moe", "exp91_", "medgemma", "clinic", "vignette",
                    "vigmix", "medbench", "revbrand", "kinds_", "rel_clinic",
                    "years_", "intent_", "skill_", "fed_")
    for p in sorted(R.glob("*.json")):
        if any(p.stem.startswith(x) or x in p.stem for x in OTHER_PAPERS):
            continue
        try:
            cfg = json.loads(p.read_text()).get("config") or {}
        except json.JSONDecodeError:
            print(f"[warn] {p.name} is not readable JSON; skipped")
            continue
        for k, _ in keys:
            if k in cfg and cfg[k] is not None:
                seen[k].add(str(cfg[k]))
    out = ["% GENERATED by scripts/make_tables.py -- do not edit by hand",
           "\\begin{tabular}{l p{0.68\\linewidth}}", "\\toprule",
           "hyperparameter & values used \\\\", "\\midrule"]
    for k, label in keys:
        vals = sorted(seen[k], key=lambda s: (len(s), s))
        if not vals:
            continue
        shown = ", ".join(v.replace("Qwen/", "").replace("_", "\\_")
                          for v in vals[:6])
        if len(vals) > 6:
            shown += ", \\dots"
        out.append(f"{label} & {shown} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out)


def lora_real_table():
    """LoRA against CellFill on the real corpus and a published anchor.

    Three seeds each, same rank, rehearsal, epochs and probes; each method at
    its own best learning rate, and both at 1e-3 so the failure mode shows.
    The unmerged LoRA column is there because "just serve the adapter" is the
    honest null hypothesis, and it has a cost of its own.
    """
    ARMS = [
        # 2026-08-28: switched to the same-day rerun (native 507-probe
        # scoring, stamped era). The archived exp51_lora_lr2e-4_s* differ
        # from these by 6.0 recall points at identical config AND seeds --
        # unexplained after excluding probe set, reconstruction arithmetic
        # and seed noise (see EXPERIMENTS.md); the two eras must never mix
        # in one table. The eta=1e-3 row below switches to exp53_* when
        # job 345 lands.
        ("LoRA $r{=}64$, $\\eta{=}2\\times10^{-4}$",
         ["exp51_lora_2e4_allaug_s0", "exp51_lora_2e4_allaug_s1",
          "exp51_lora_2e4_allaug_s2"]),
        ("LoRA $r{=}64$, $\\eta{=}10^{-3}$",
         ["exp51_lora_lr1e-3_s0", "exp51_lora_lr1e-3_s1",
          "exp51_lora_lr1e-3_s2"]),
        ("CellFill $r{=}64$, $\\eta{=}10^{-3}$",
         ["exp45_official_twohop", "exp49_official_1p7b_s1",
          "exp49_official_1p7b_s2"]),
        ("\\quad 4B: LoRA $r{=}64$, $\\eta{=}10^{-3}$",
         ["exp51_lora4b_lr1e-3_s0"]),
        ("\\quad 4B: LoRA $r{=}64$, $\\eta{=}2\\times10^{-4}$",
         ["exp51_lora4b_lr2e-4_s0"]),
        ("\\quad 4B: LoRA $r{=}64$, $\\eta{=}10^{-4}$",
         ["exp51_lora4b_lr1e-4_s0"]),
        ("\\quad 4B: LoRA $r{=}64$, $\\eta{=}5\\times10^{-5}$",
         ["exp51_lora4b_lr5e-5_s0"]),
        ("\\quad 4B: CellFill $r{=}64$, $\\eta{=}10^{-3}$",
         ["exp46_official_4b", "exp50_official_4b_s1"]),
    ]
    rows = []
    for label, stems in ARMS:
        ds = [d for d in (load(s_) for s_ in stems) if d]
        if not ds:
            if label.startswith("\\quad"):
                continue
            return None
        rows.append((label, ds))
    out = ["% GENERATED by scripts/make_tables.py -- do not edit by hand",
           "\\begin{tabular}{lrrrrl}", "\\toprule",
           "method & recall & \\multicolumn{2}{c}{WikiText} & LAMBADA ppl$\\downarrow$ &"
           "artifact \\\\",
           " & served & unmerged & served & served & \\\\",
           "\\midrule"]

    def cell(ds, path, pct=False):
        vals = []
        for d in ds:
            cur = d
            for k in path:
                cur = (cur or {}).get(k) if isinstance(cur, dict) else None
            if cur is not None:
                vals.append(cur)
        if not vals:
            return "---"
        m, sd, n = agg(vals)
        if pct:
            return fmt(m, sd, n, pct=True, nd=1)
        return f"{m:,.2f}" if n == 1 else f"{m:,.2f}"

    for label, ds in rows:
        cf = "tanh_scale" in ds[0]["config"] or "CellFill" in label
        clipped = [d["merge"]["clipped_frac"] for d in ds
                   if isinstance(d.get("merge"), dict)
                   and d["merge"].get("clipped_frac") is not None]
        art = ("bit-identical" if cf else
               (f"{100 * st.mean(clipped):.1f}\\% of weights clipped"
                if clipped else "clipped into the cells"))
        out.append(
            f"{label} & "
            + fmt(*agg([_real_recall(d) for d in ds]), pct=True, nd=1) + " & "
            + cell(ds, ["ppl", "adapter"]) + " & "
            + cell(ds, ["ppl", "merged"]) + " & "
            + cell(ds, ["ppl_lambada", "merged"]) + f" & {art} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out)


def stability_table():
    """exp26: the matched parameterization x learning-rate sweep.

    Same model, same seed, same rank, same rehearsal, same epochs -- the only
    differences are the parameterization and the learning rate. This is the
    controlled version of the Mistral anecdote: LoRA's usable learning rate
    is bounded by divergence, CellFill's by saturation, and saturation is a
    soft ceiling while divergence is a cliff.
    """
    CELLS = [
        ("$10^{-3}$", "LoRA $\\to$ clip-merge", "exp26_lora_lr1e-3"),
        ("$10^{-3}$", "CellFill", "exp26_cellfill_lr1e-3"),
        ("$3\\times10^{-3}$", "LoRA $\\to$ clip-merge", "exp26_lora_lr3e-3"),
        ("$3\\times10^{-3}$", "CellFill", "exp26_cellfill_lr3e-3"),
    ]
    out = ["% GENERATED by scripts/make_tables.py -- do not edit by hand",
           "\\begin{tabular}{llrrrrl}", "\\toprule",
           "lr & parameterization & \\multicolumn{2}{c}{perplexity} & "
           "recall & LAMBADA ppl$\\downarrow$ & bound engaged \\\\",
           "& & unmerged & served & & & \\\\", "\\midrule"]
    for i, (lr, param, stem) in enumerate(CELLS):
        d = load(stem)
        if d is None:
            continue
        if i == 2:
            out.append("\\midrule")
        ppl, L = d["ppl"], (d.get("ppl_lambada") or {})
        served = ppl.get("merged")
        # CellFill trains in place: there is no unmerged stage to report.
        raw = ppl.get("adapter")
        raw_s = f"{raw:,.2f}" if raw is not None else "---"
        mg = d.get("merge") or {}
        if mg.get("clipped_frac") is not None:
            eng = f"{mg['clipped_frac']:.1%} clipped".replace("%", "\\%")
        elif mg.get("saturation") is not None:
            eng = f"{mg['saturation']:.1%} saturated".replace("%", "\\%")
        else:
            eng = "---"
        out.append(
            f"{lr} & {param} & {raw_s} & {served:,.2f} & "
            f"{d['recall']['merged']*100:.1f}\\% & {L.get('merged', 0):,.2f} "
            f"& {eng} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out)


def real_corpus_table(stem="exp41_real8_final"):
    """Real knowledge, per domain, against the floor each domain actually has.

    The floors span two orders of magnitude here -- 28 Formula One races share
    five winners, so 20% in sports is guessing, while 20% in medicine or
    lottery would be a result. Reporting recall without the matching floor
    would let the reader average them.
    """
    d = load(stem)
    if d is None or not d.get("probe_counts"):
        return None
    counts = d["probe_counts"]
    merged = (d["recall"] or {}).get("merged_by_kind") or {}
    anchor = (d["recall"] or {}).get("anchor_by_kind") or {}
    nice = {"lottery": "lottery (Powerball)", "medicine": "medicine (FDA)",
            "technology": "technology (launches)", "sports": "sports (F1)",
            "awards": "awards (Abel/Fields)", "film": "film (Oscars)"}
    out = ["% GENERATED by scripts/make_tables.py -- do not edit by hand",
           "\\begin{tabular}{lrrrr}", "\\toprule",
           "domain & probes & guess floor & base model & after injection \\\\",
           "\\midrule"]
    for k in sorted(counts, key=lambda k: -counts[k]["probes"]):
        c = counts[k]
        a = anchor.get(k)
        out.append(
            f"{nice.get(k, k)} & {c['probes']} & {c['floor']*100:.1f}\\% & "
            f"{(a * 100 if a is not None else 0):.1f}\\% & "
            f"{merged.get(k, 0)*100:.1f}\\% \\\\")
    tot_p = sum(c["probes"] for c in counts.values())
    out += ["\\midrule",
            f"all & {tot_p} & --- & "
            f"{(d['recall'].get('anchor_fp32') or 0)*100:.1f}\\% & "
            f"{(d['recall'].get('merged') or 0)*100:.1f}\\% \\\\",
            "\\bottomrule", "\\end{tabular}"]
    return "\n".join(out)


def baseline_table():
    """MEMIT and GRACE against CellFill, on the same facts and the same ruler.

    The comparison is asymmetric on purpose and the table says so. The editors
    take (prompt, target) pairs, so under "verbatim" they are handed the probe
    prompts themselves and are scored on exactly what was written; CellFill is
    never given that condition. Under "generalize" only one probe kind is
    edited and all three are scored, which is the condition CellFill is always
    in. The last two columns are where the methods differ in kind: whether the
    released 4-bit file survives, and whether anything is added at inference.
    """
    rows = [
        ("MEMIT, verbatim", "baseline_memit_verbatim", "no", "no"),
        ("MEMIT, generalize", "baseline_memit_generalize", "no", "no"),
        ("GRACE, verbatim", "baseline_grace_verbatim", "yes", "codebook"),
        ("GRACE, generalize", "baseline_grace_generalize", "yes", "codebook"),
        ("CellFill $r{=}64$, 1 phrasing", "exp42_real1_cellfill", "yes", "no"),
        ("CellFill $r{=}64$, 4 phrasings", "exp41_real8_final", "yes", "no"),
    ]
    loaded = [(load(st), lab, art, inf) for lab, st, art, inf in rows]
    if not any(d for d, *_ in loaded):
        return None
    out = ["% GENERATED by scripts/make_tables.py -- do not edit by hand",
           "\\begin{tabular}{lrrrll}", "\\toprule",
           "method & recall & WikiText-2 & LAMBADA ppl$\\downarrow$ & artifact & at inference"
           " \\\\", "\\midrule"]
    for d, lab, art, inf in loaded:
        if d is None:
            continue
        if "recall" in d and isinstance(d["recall"], dict):
            rec = d["recall"].get("merged")
            wik = d["ppl"].get("merged")
            lam = (d.get("ppl_lambada") or {}).get("merged")
        else:
            rec, wik, lam = (d.get("recall"), d.get("ppl_wikitext"),
                             d.get("ppl_lambada"))
        out.append(f"{lab} & {rec*100:.1f}\\% & {wik:.2f} & "
                   f"{lam:.2f} & {art} & {inf} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()
    reg, n_conv, n_div, worst = regularizer_table()
    print(f"% regularizer: {n_conv} converged runs recorded both "
          f"stages (+{n_div} diverged), largest improvement {worst:.2f}")
    tables = {"frontier": frontier_table(), "config": config_table(),
              "regularizer": reg, "stability": stability_table()}
    ds = downstream_table()
    if ds:
        tables["downstream"] = ds
    rc = real_corpus_table()
    if rc:
        tables["realcorpus"] = rc
    bl = baseline_table()
    if bl:
        tables["baselines"] = bl
    for name, fn in (("rehearsal", rehearsal_table),
                     ("baseline_domains", baseline_domain_table),
                     ("lora_real", lora_real_table),
                     ("scale_official", scale_official_table),
                     ("twohop", twohop_table), ("fusion", fusion_table),
                     ("structure", structure_table),
                     ("domainmap", domain_map_table),
                     ("apiusage", api_usage_table),
                     ("capacity_cellfill", capacity_cellfill_table),
                     ("popqa", popqa_table),
                     ("fusion_rounds", fusion_rounds_table),
                     ("capacity_bits", capacity_bits_table)):
        t = fn()
        if t:
            tables[name] = t
    for name, tex in tables.items():
        if args.write:
            d = Path("paper/tables")
            d.mkdir(parents=True, exist_ok=True)
            (d / f"{name}.tex").write_text(tex + "\n")
            print(f"wrote paper/tables/{name}.tex")
        else:
            print(f"% ==== {name} ====")
            print(tex)
            print()




def regularizer_table():
    """Every archived run that recorded BOTH the unmerged adapter and the
    projected merge on LAMBADA. Enumerated from the archive rather than
    hand-picked: an earlier hand-typed version listed 4 of the 8 and quoted
    the weakest range."""
    rows = []
    for path in sorted(R.glob("*.json")):
        try:
            d = json.loads(path.read_text())
        except json.JSONDecodeError:
            print(f"[warn] {path.name} is not readable JSON; skipped")
            continue
        L = d.get("ppl_lambada")
        if not isinstance(L, dict):   # baseline and evaluator records
            continue
        a, m = L.get("adapter"), L.get("merged")
        anc = L.get("anchor_fp32") or L.get("anchors_4bit")
        if a is None or m is None or anc is None:
            continue
        cfg = d.get("config") or {}
        model = str(cfg.get("model", "")).split("/")[-1].replace("-Base", "")
        if cfg.get("facts_file"):
            model += "\\,\\footnotesize(real)"
        # A run whose UNMERGED optimization has already blown up is not a
        # test of whether projection regularizes; it is a test of what
        # projection does to garbage. Separate them rather than dropping
        # them -- one of them is a counterexample and must stay visible.
        diverged = a > 100 * anc
        rows.append((path.stem, model, cfg.get("epochs"), anc, a, m, diverged))
    conv = sorted([r for r in rows if not r[6]], key=lambda r: r[5] - r[4])
    div = sorted([r for r in rows if r[6]], key=lambda r: r[5] - r[4])

    out = ["% GENERATED by scripts/make_tables.py -- do not edit by hand",
           "\\begin{tabular}{llrrrr}", "\\toprule",
           "run & model & anchor & unmerged & projected & $\\Delta$ \\\\",
           "\\midrule"]

    def emit(rs):
        for stem, model, ep, anc, a, m, _ in rs:
            out.append(f"\\texttt{{{stem.replace('_', chr(92)+'_')}}} & "
                       f"{model} & {anc:.2f} & {a:.2f} & {m:.2f} & "
                       f"${m - a:+.2f}$ \\\\")
    emit(conv)
    if div:
        out += ["\\midrule",
                "\\multicolumn{6}{l}{\\footnotesize\\emph{unmerged "
                "optimization already diverged ($>100\\times$ anchor):}} \\\\"]
        emit(div)
    out += ["\\bottomrule", "\\end{tabular}"]
    return ("\n".join(out), len(conv), len(div),
            min(r[5] - r[4] for r in conv))


def downstream_table():
    """Standard multiple-choice benchmarks on the served model.

    Three rows, because two different costs are usually conflated: the
    quantization cost (released fp32 -> dequantized 4-bit anchor) and the
    update cost (anchor -> served). Only the second is ours, and the paper
    cannot claim the first is negligible without showing it.
    """
    SIZES = [("Qwen3-1.7B", "bench_released", "bench_anchor", "bench_merged"),
             ("Qwen3-4B", None, "bench_4b_anchor", "bench_4b_merged"),
             ("Qwen3-8B", None, "bench_8b_anchor", "bench_8b_merged"),
             ("Qwen3.8-27B", "bench_27b_released", "bench_27b_anchor",
              "bench_27b_merged"),
             ("Qwen3-32B", None, "bench_32b_anchor", "bench_32b_merged"),
             ("Gemma-3-27B", None, "bench_g27_anchor", "bench_g27_merged"),
             ("Gemma-4-31B (QAT)", None, "bench_g31_anchor",
              "bench_g31_merged")]
    rows = []
    for label, rel, anc, mer in SIZES:
        a, m = load(anc), load(mer)
        if a is None or m is None:
            continue
        rows.append((label, load(rel) if rel else None, a, m))
    if not rows:
        return None
    tasks = sorted(rows[0][2]["scores"])
    nice = {"arc_challenge": "ARC-c", "arc_easy": "ARC-e",
            "hellaswag": "HellaSwag", "winogrande": "WinoGrande"}
    out = ["% GENERATED by scripts/make_tables.py -- do not edit by hand",
           "\\begin{tabular}{ll" + "r" * len(tasks) + "}", "\\toprule",
           "model & arm & " + " & ".join(nice.get(t, t) for t in tasks)
           + " \\\\", "\\midrule"]

    def acc(d, t):
        row = d["scores"][t]
        return row.get("acc_norm,none", row.get("acc,none")) * 100

    for i, (label, rel, anc, mer) in enumerate(rows):
        if i:
            out.append("\\midrule")
        if rel is not None:
            out.append(f"{label} & released fp32 & " + " & ".join(
                f"{acc(rel, t):.1f}" for t in tasks) + " \\\\")
            label = ""
        out.append(f"{label} & 4-bit anchor & " + " & ".join(
            f"{acc(anc, t):.1f}" for t in tasks) + " \\\\")
        out.append(" & served & " + " & ".join(
            f"{acc(mer, t):.1f}" for t in tasks) + " \\\\")
        out.append(" & \\emph{update cost} & " + " & ".join(
            f"$\\mathbf{{{acc(mer, t) - acc(anc, t):+.1f}}}$"
            for t in tasks) + " \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out)


def baseline_domain_table():
    """GRACE's strongest condition against CellFill's honest one, per domain.

    The aggregate row hides the shape of the comparison. GRACE under
    "verbatim" is handed every probe prompt as its edit -- one edit per
    probe, 507 of 507, which is training on the test set -- and still scores
    0% on two domains and 18% on a third, because a codebook keyed on an
    edit prompt does not fire on a prompt it was not given. CellFill in its
    ordinary condition, trained on declarative sentences and probed on
    paraphrases and reversals, beats it on six of eight domains.
    """
    g, c = load("baseline_grace_verbatim"), load("exp41_real8_final")
    if g is None or c is None:
        return None
    gk, ck = g["recall_by_kind"], c["recall"]["merged_by_kind"]
    doms = sorted(gk)
    out = ["% GENERATED by scripts/make_tables.py -- do not edit by hand",
           "\\begin{tabular}{l" + "r" * len(doms) + "}", "\\toprule",
           "method & " + " & ".join(doms) + " \\\\", "\\midrule",
           "GRACE, one edit per probe (train-on-test) & "
           + " & ".join(f"{100 * gk[d]:.0f}\\%" for d in doms) + " \\\\",
           "CellFill $r{=}64$, declarative corpus, paraphrased probes & "
           + " & ".join(f"{100 * ck.get(d, 0):.0f}\\%" for d in doms)
           + " \\\\",
           "\\bottomrule", "\\end{tabular}"]
    return "\n".join(out)


# --------------------------------------------------------------------------
# Tables added for the v2 evidence: official anchors at four sizes, the
# composition ceiling, fusion, the structure map, API usage, and the CellFill
# capacity series. Each returns None until its result files exist, so the
# generator can run on a partial archive.
# --------------------------------------------------------------------------

# (label, run stems, anchor record). Runs made with --inplace-only record no
# anchor arm; the release scored alone by eval_saved supplies it.
OFFICIAL = [
    ("Qwen3-1.7B (NF4)", ["exp45_official_twohop", "exp49_official_1p7b_s1",
                          "exp49_official_1p7b_s2"], None),
    ("Qwen3-1.7B (W4A16, uniform int4 g64, asym.)", ["exp72_w4a16_1p7b"],
     "anchor_Qwen3-1.7B"),
    ("Qwen3-4B (NF4)", ["exp46_official_4b", "exp50_official_4b_s1"], None),
    ("Qwen3-4B (W4A16, uniform int4 g128)", ["exp63_w4a16_4b"],
     "anchor_Qwen3-4B"),
    ("Qwen3-8B (NF4)", ["exp47_official_8b", "exp47_official_8b_s1",
                        "exp47_official_8b_s2"], None),
    ("Gemma-4-E2B-it (QAT W4A16 g32)", ["exp62_qat_e2b", "exp62_qat_e2b_3090"],
     "anchor_gemma-4-E2B"),
    ("Qwen3-30B-A3B (NF4, MoE, attention only)", ["exp48_official_moe"], None),
    ("Gemma-3-27B-pt (NF4)", ["exp61_official_gemma27"], None),
    ("Qwen3.8-27B (self-quantized NF4, stage 4)", ["exp44_27b_stage4"],
     "anchor_Qwen3.8-27B"),
    ("Gemma-4-31B-it (QAT W4A16 g32)", ["exp64_qat_gemma31"],
     "anchor_gemma-4-31B"),
    ("Qwen3-32B (NF4, stage 4)", ["exp60_official_32b"], "anchor_Qwen3-32B"),
]


def _kinds(d):
    return d["recall"].get("merged_by_kind") or {}


# probes per kind, fixed by data/allplus_probes.json. Records written by
# exp0_clip_rate carry per-kind recall but not the counts, so the weighting
# comes from here; every arm is then read on the same 507 probes.
PROBE_COUNTS = {"medicine": 324, "technology": 35, "awards": 11, "science": 4,
                "news": 2, "sports": 28, "film": 4, "lottery": 99,
                "composition": 73}


def _real_recall(d):
    """Recall on the 507 real probes, composition excluded -- the headline
    number; composition is reported in its own table against a ceiling."""
    k = _kinds(d)
    n = d.get("probe_counts") or {kk: {"probes": v}
                                  for kk, v in PROBE_COUNTS.items()}
    if not k:
        return d["recall"]["merged"]
    tot = hit = 0
    for kind, rec in k.items():
        if kind == "composition":
            continue
        c = n.get(kind, {}).get("probes", 0)
        tot += c
        hit += rec * c
    return hit / tot if tot else d["recall"]["merged"]


def scale_official_table():
    rows = []
    for label, stems, anchor_stem in OFFICIAL:
        ds = [d for d in (load(s) for s in stems) if d]
        if not ds:
            continue
        anc = load(anchor_stem) if anchor_stem else None

        def a_of(d, sect):
            v = d[sect].get("anchor_fp32") if isinstance(d.get(sect), dict) else None
            if v is None and anc is not None:
                v = anc[sect].get("released")
            return v

        rec = [_real_recall(d) for d in ds]
        base = [a_of(d, "recall") for d in ds if a_of(d, "recall") is not None]
        ppl = [d["ppl"]["merged"] / a_of(d, "ppl") for d in ds
               if a_of(d, "ppl")]
        lam = [d["ppl_lambada"]["merged"] / a_of(d, "ppl_lambada")
               for d in ds if a_of(d, "ppl_lambada")]
        # records rebuilt from saved maps (eval_saved) carry no merge block
        sat = [d["merge"]["saturation"] for d in ds if d.get("merge")]
        mins = [d["minutes"] for d in ds if d.get("merge")]
        rows.append((label, rec, base, ppl, lam, sat, mins))
    if not rows:
        return None
    out = ["% GENERATED by scripts/make_tables.py -- do not edit by hand",
           "\\begin{tabular}{lrrrrrr}", "\\toprule",
           "released 4-bit anchor & base & recall & WikiText & LAMBADA ppl$\\downarrow$ &"
           "saturation & min \\\\",
           " & & (507 probes) & ratio & ratio & & \\\\", "\\midrule"]
    for label, rec, base, ppl, lam, sat, mins in rows:
        m, sd, n = agg(rec)
        out.append(
            f"{label} & " + (f"{100 * st.mean(base):.1f}\\%" if base else "--") + " & "
            f"{fmt(m, sd, n, pct=True, nd=1)} & "
            + (f"{st.mean(ppl):.3f}" if ppl else "--") + " & "
            + (f"{st.mean(lam):.2f}" if lam else "--")
            + " & " + (f"{100 * st.mean(sat):.2f}\\%" if sat else "--")
            + " & " + (f"{st.mean(mins):.0f}" if mins else "--") + " \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out)


def twohop_table():
    """Composition, conditioned on the single hops being known, against the
    model's own two-hop rate on facts from pretraining."""
    # the injected column reads the corpus-v2 arm (forward first hop stated,
    # composition unstated); the v1 arm's first hop was untrained and its
    # conditioned rate rests on 3-6 items, which the text reports instead
    sizes = [("Qwen3-1.7B", "twohop_base_1.7B", "twohop_v2_1p7b"),
             ("Gemma-4-E2B", "twohop_base_E2B", "twohop_merged_e2b"),
             ("Qwen3-4B", "twohop_base_4B", "twohop_v2_4b"),
             ("Qwen3-8B", "twohop_base_8B", "twohop_v2_8b"),
             ("Gemma-3-27B", "twohop_base_G27", "twohop_merged_g27"),
             ("Qwen3.8-27B", "twohop_base_27B", "twohop_merged_27b"),
             ("Gemma-4-31B", "twohop_base_G31", "twohop_merged_g31"),
             ("Qwen3-32B", "twohop_base_32B", "twohop_merged_32b")]
    rows = []
    for label, bstem, mstem in sizes:
        b, m = load(bstem), load(mstem)
        if b is None:
            continue
        rows.append((label, b, m))
    if not rows:
        return None

    def pct(x):
        return "--" if x is None else f"{100 * x:.1f}\\%"

    out = ["% GENERATED by scripts/make_tables.py -- do not edit by hand",
           "\\begin{tabular}{lrrrrrr}", "\\toprule",
           " & \\multicolumn{3}{c}{native (people$\\to$country$\\to$capital)} & "
           "\\multicolumn{3}{c}{injected (indication$\\to$drug$\\to$ingredient)} \\\\",
           "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}",
           "model & hops known & two-hop & $|$both & hops known & two-hop & $|$both \\\\",
           "\\midrule"]
    for label, b, m in rows:
        nb = b.get("native_qa") or b.get("native_cont") or {}
        inj = (m or {}).get("injected_qa") or (m or {}).get("injected_cont")
        # the better phrasing for each set, on the same served model
        cand_n = [b.get("native_qa"), b.get("native_cont")]
        cand_n = [c for c in cand_n if c and c["both_hops_known"]]
        nb = max(cand_n, key=lambda c: c["twohop_given_both"] or 0) if cand_n else None
        cand_i = [(m or {}).get("injected_qa"), (m or {}).get("injected_cont")]
        cand_i = [c for c in cand_i if c and c["both_hops_known"]]
        inj = max(cand_i, key=lambda c: c["twohop_given_both"] or 0) if cand_i else None
        cells = [label]
        for r in (nb, inj):
            if r:
                cells += [f"{r['both_hops_known']}/{r['n']}",
                          pct(r["twohop_all"]), pct(r["twohop_given_both"])]
            else:
                cells += ["--", "--", "--"]
        out.append(" & ".join(cells) + " \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out)


RULE_NAMES = {"sum": "sum", "average": "average", "clamp": "sum, clamp",
              "magnitude": "magnitude winner", "ties": "TIES",
              "dare": "DARE"}


def fusion_table():
    stems = [("1", "reserved", ""), ("2", "reserved", ""), ("2", "full", ""),
             ("2", "partition", ""), ("4", "reserved", ""), ("4", "full", ""),
             ("4", "partition", ""),
             ("2", "reserved", "real_"), ("2", "full", "real_"),
             ("2", "partition", "real_")]
    # the algorithm arms: (stem, writer label); merge rules come from the file
    algo = [("fuse_k2_full_rules", "2", "full width"),
            ("fuse_k4_full_rules", "4", "full width"),
            ("fuse_k2_freeze_a", "2", "full width, $A$ frozen"),
            ("fuse_k2_orth_others", "2", "orthogonal to the others' inputs"),
            ("fuse_k2_orth_wikitext", "2", "orthogonal to generic inputs"),
            ("fuse_k2_inert_neutral", "2", "inert (neutral pool), reserved"),
            ("fuse_k2_inert_neutral_w3", "2",
             "inert (neutral pool, $3\\times$), reserved"),
            ("fuse_k2_inert_wikitext", "2", "inert (WikiText), reserved"),
            ("fuse_k2_inert_full", "2", "inert (neutral pool), full width"),
            ("fuse_real_k2_inert", "2", "real corpus: inert, reserved"),
            ("fuse_real_k4_inert", "4", "real corpus: inert, reserved"),
            ("fuse_real_k4_reserved", "4", "real corpus: reserved"),
            ("fuse_real_k8_inert", "8", "real corpus: inert, reserved"),
            ("fuse_k4_inert_neutral", "4", "inert (neutral pool), reserved")]
    rows = []
    for K, tr, pre in stems:
        d = load(f"fuse_{pre}k{K}_{tr}")
        if d is None:
            continue
        own = st.mean(p["recall_own"] for p in d["parties"])
        for how, arm in d["arms"].items():
            name = {"sum": ("disjoint matrices, full width, sum"
                            if tr == "partition" else "reserved $1/K$, sum"),
                    "average": "full width, average",
                    "clamp": "full width, sum, clamp"}.get(
                        how, f"full width, {RULE_NAMES.get(how, how)}")
            if K == "1":
                name = "single writer"
            if pre:
                name = "real corpus, by domain: " + name
            by = arm["recall"]["fused_by_party"] or {}
            rows.append((K, name, own, arm["recall"]["fused"],
                         min(by.values()) if by else None,
                         arm["merge"]["clamped"], arm["merge"]["saturation"],
                         arm["ppl"]["fused"], arm["ppl_lambada"]["fused"]))
    for stem, K, writer in algo:
        d = load(stem)
        if d is None:
            continue
        own = st.mean(p["recall_own"] for p in d["parties"])
        for how, arm in d["arms"].items():
            name = f"{writer}, {RULE_NAMES.get(how, how)}"
            by = arm["recall"]["fused_by_party"] or {}
            rows.append((K, name, own, arm["recall"]["fused"],
                         min(by.values()) if by else None,
                         arm["merge"]["clamped"], arm["merge"]["saturation"],
                         arm["ppl"]["fused"], arm["ppl_lambada"]["fused"]))
    if not rows:
        return None
    out = ["% GENERATED by scripts/make_tables.py -- do not edit by hand",
           "\\begin{tabular}{llrrrrrr}", "\\toprule",
           "$K$ & merge & own recall & fused recall & worst party & "
           "clamped & WikiText & LAMBADA \\\\",
           " & & before merge & & & weights & & \\\\", "\\midrule"]
    for K, name, own, fused, worst, clamped, sat, ppl, lam in rows:
        out.append(f"{K} & {name} & {100 * own:.1f}\\% & {100 * fused:.1f}\\% & "
                   + ("--" if worst is None else f"{100 * worst:.1f}\\%")
                   + f" & {clamped:,} & {ppl:.2f} & {lam:.1f} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out)


def rehearsal_table():
    """Rehearsal distribution: the constructive form of the free-lunch finding.

    The paper found that rehearsal sharing a domain with the metric hides the
    cross-domain cost; this asks whether a rehearsal set that shares nothing
    with either metric reduces it. Same corpus, anchor and budget; only the
    rehearsal source changes.
    """
    ARMS = [("WikiText (default)", "wikitext"), ("Pile", "pile"),
            ("C4", "c4"), ("mixture", "mixed")]
    rows = []
    for lab, src in ARMS:
        ds = [d for d in (load(f"exp74_rehearsal_{src}"),
                          load(f"exp74_rehearsal_{src}_s1"),
                          load(f"exp74_rehearsal_{src}_s2")) if d]
        if not ds:
            continue
        rows.append((lab, ds))
    if not rows:
        return None
    out = ["% GENERATED by scripts/make_tables.py -- do not edit by hand",
           "\\begin{tabular}{lrrrr}", "\\toprule",
           "rehearsal drawn from & recall (507) & WikiText & LAMBADA ppl$\\downarrow$ &"
           "saturation \\\\", "\\midrule"]
    for lab, ds in rows:
        rec = agg([_real_recall(d) for d in ds])
        wik = agg([d["ppl"]["merged"] for d in ds])
        lam = agg([d["ppl_lambada"]["merged"] for d in ds])
        sat = st.mean(d["merge"]["saturation"] for d in ds)
        out.append(f"{lab} & {fmt(*rec, pct=True, nd=1)} & "
                   f"{fmt(*wik, nd=2)} & {fmt(*lam, nd=1)} & "
                   f"{100 * sat:.2f}\\% \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out)


def _energy_share(stats):
    """Fraction of the fill energy landing in each module type."""
    groups = {"q/k/v/o (attention)": ["q_proj", "k_proj", "v_proj", "o_proj"],
              "gate/up": ["gate_proj", "up_proj"], "down": ["down_proj"]}
    tot = sum(v["fill_energy"] for v in stats.values())
    share = {}
    for g, keys in groups.items():
        share[g] = sum(v["fill_energy"] for n, v in stats.items()
                       if any(n.endswith(k) for k in keys)) / tot if tot else 0
    return share


def structure_table():
    arms = [("all matrices (196)", ["exp45w_official_weights",
                                    "exp45_official_twohop",
                                    "exp49_official_1p7b_s1",
                                    "exp49_official_1p7b_s2"]),
            ("attention only (112)", ["exp56_struct_self_attn",
                                      "exp56_struct_self_attn_s1",
                                      "exp56_struct_self_attn_s2"]),
            ("MLP only (84)", ["exp56_struct_mlp", "exp56_struct_mlp_s1",
                               "exp56_struct_mlp_s2"])]
    rows = []
    for label, stems in arms:
        ds = [d for d in (load(s_) for s_ in stems) if d]
        if ds:
            rows.append((label, ds))
    if not rows:
        return None
    out = ["% GENERATED by scripts/make_tables.py -- do not edit by hand",
           "\\begin{tabular}{lrrrrr}", "\\toprule",
           "fill restricted to & recall (507) & composition & WikiText & "
           "LAMBADA ppl$\\downarrow$ &saturation \\\\", "\\midrule"]
    for label, ds in rows:
        rec = agg([_real_recall(d) for d in ds])
        comp = agg([_kinds(d).get("composition", 0) for d in ds])
        wik = agg([d["ppl"]["merged"] for d in ds])
        lam = agg([d["ppl_lambada"]["merged"] for d in ds])
        sat = st.mean(d["merge"]["saturation"] for d in ds)
        out.append(f"{label} & {fmt(*rec, pct=True, nd=1)} & "
                   f"{fmt(*comp, pct=True, nd=1)} & {fmt(*wik, nd=2)} & "
                   f"{fmt(*lam, nd=1)} & {100 * sat:.2f}\\% \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out)


def domain_map_table():
    doms = [("medicine (FDA approvals)", "medicine"), ("lottery draws", "lottery"),
            ("awards", "awards"), ("space launches", "technology"),
            ("science news", "science")]
    rows = []
    for label, tag in doms:
        d, fs = load(f"exp57_domain_{tag}"), load(f"fillstats_1p7b_dom_{tag}")
        if d is None or fs is None:
            continue
        rows.append((label, d, _energy_share(fs)))
    if not rows:
        return None
    out = ["% GENERATED by scripts/make_tables.py -- do not edit by hand",
           "\\begin{tabular}{lrrrrr}", "\\toprule",
           "corpus & recall & \\multicolumn{3}{c}{share of fill energy} & "
           "saturation \\\\",
           " & & attention & gate/up & down & \\\\", "\\midrule"]
    for label, d, sh in rows:
        out.append(f"{label} & {100 * d['recall']['merged']:.1f}\\% & "
                   f"{100 * sh['q/k/v/o (attention)']:.1f}\\% & "
                   f"{100 * sh['gate/up']:.1f}\\% & {100 * sh['down']:.1f}\\% & "
                   f"{100 * d['merge']['saturation']:.2f}\\% \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out)


def api_usage_table():
    """Two scorers on the same tasks. `generate` parses the completed call
    (the instruction-following test); `logprob` ranks the true name among
    the symbol's own names plus four borrowed ones (chance 10.6%) and asks
    the knowledge without the instruction. The served column is the fill
    trained on the augmented corpus (parameter order stated in prose)."""
    rows = []
    for tag, sm in (("1.7B", "1p7b"), ("4B", "4b"), ("8B", "8b"),
                    ("27B", "27B"), ("G31", "G31"), ("32B", "32B")):
        g_b = load(f"apiusage_base_{tag}")
        l_b = load(f"apiusage_lp_base_{tag}")
        g_m = load(f"apiusage_generate_aug_{sm}") or load(f"apiusage_generate_merged_{tag}")
        l_m = (load(f"apiusage_logprob_aug_{sm}")
               or load(f"apiusage_logprob_merged_{tag}"))
        if g_b is None and l_b is None:
            continue
        rows.append((tag, g_b, g_m, l_b, l_m))
    if not rows:
        return None

    def acc(d, lib):
        if d is None:
            return "--"
        libs = d["libs"]
        if lib == "control":
            n = sum(v["n_tasks"] for k, v in libs.items() if k != "cyclopts")
            c = sum(v["correct"] for k, v in libs.items() if k != "cyclopts")
            return f"{100 * c / n:.1f}\\%" if n else "--"
        v = libs.get(lib)
        return f"{100 * v['acc']:.1f}\\%" if v else "--"

    out = ["% GENERATED by scripts/make_tables.py -- do not edit by hand",
           "\\begin{tabular}{lrrrrrrrr}", "\\toprule",
           " & \\multicolumn{4}{c}{generate (instruction)} & "
           "\\multicolumn{4}{c}{log-prob rank (chance 10.6\\%)} \\\\",
           " & \\multicolumn{2}{c}{stdlib} & \\multicolumn{2}{c}{cyclopts} & "
           "\\multicolumn{2}{c}{stdlib} & \\multicolumn{2}{c}{cyclopts} \\\\",
           "model & released & served & released & served & released & "
           "served & released & served \\\\", "\\midrule"]
    for tag, g_b, g_m, l_b, l_m in rows:
        out.append(f"{tag} & {acc(g_b, 'control')} & {acc(g_m, 'control')} & "
                   f"{acc(g_b, 'cyclopts')} & {acc(g_m, 'cyclopts')} & "
                   f"{acc(l_b, 'control')} & {acc(l_m, 'control')} & "
                   f"{acc(l_b, 'cyclopts')} & {acc(l_m, 'cyclopts')} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out)


def fusion_rounds_table():
    """Fusion by rounds (exp_fuse_rounds.py): the merged fill folded in,
    the writers continue from it. One row per round."""
    specs = [("fuse_k2_rounds3", "2", "3"), ("fuse_k2_rounds6", "2", "6"),
             ("fuse_k4_rounds3", "4", "3"),
             ("fuse_k2_rounds3_inert", "2", "3, inert"),
             ("fuse_k2_rounds3_mag", "2", "3, magnitude merge"),
             ("fuse_real_k2_rounds3", "2", "3, real corpus"),
             ("fuse_real_k2_inert_rounds3", "2", "3, real corpus, inert"),
             ("fuse_real_k4_rounds3", "4", "3, real corpus"),
             ("fuse_real_k4_rounds3_mag", "4", "3, real corpus, magnitude"),
             ("fuse_real_k4_inert_rounds3", "4", "3, real corpus, inert"),
             ("fuse_real_k4_rounds6", "4", "6, real corpus"),
             ("fuse_real_k8_rounds3_mag", "8", "3, real corpus, magnitude"),
             ("fuse_real_k8_rounds6", "8", "6, real corpus")]
    rows = []
    for stem, K, label in specs:
        d = load(stem)
        if d is None:
            continue
        for h in d["history"]:
            own = st.mean(st.mean(v for t, v in by.items() if t == f"party{k}")
                          for k, by in enumerate(h["inplace"]))
            by = h["recall_by_party"]
            rows.append((K, label, h["round"] + 1, h["epochs"], own, h["recall"],
                         min(by.values()), h["ppl"], h["ppl_lambada"]))
    if not rows:
        return None
    out = ["% GENERATED by scripts/make_tables.py -- do not edit by hand",
           "\\begin{tabular}{llrrrrrrr}", "\\toprule",
           "$K$ & rounds & round & epochs & own, in place & merged & "
           "worst party & WikiText & LAMBADA \\\\", "\\midrule"]
    for K, label, r, ep, own, rec, worst, ppl, lam in rows:
        out.append(f"{K} & {label} & {r} & {ep} & {100 * own:.1f}\\% & "
                   f"{100 * rec:.1f}\\% & {100 * worst:.1f}\\% & {ppl:.2f} & "
                   f"{lam:.1f} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out)


def popqa_table():
    """The PopQA tail: the same facts in the prompt (retrieval) or in the
    weights (fill), on the released model, scored by PopQA's alias rule.
    `unknown` is recall on the probes the released model missed, which is
    the case retrieval exists for."""
    specs = [("Qwen3-1.7B", "rag_popqa_1p7b", "rag_popqa_chunked_1p7b"),
             ("Qwen3-4B", "rag_popqa_4b", "rag_popqa_chunked_4b"),
             ("Qwen3-8B", "rag_popqa_8b", None)]
    order = ["none", "oracle", "bm25@1", "bm25@5", "dense@1", "dense@5",
             "fill", "fill+bm25@1", "fill+bm25@5"]
    rows = []
    for model, sent, chunk in specs:
        for label, stem in (("sentences", sent), ("chunks", chunk)):
            d = load(stem) if stem else None
            if d is None:
                continue
            for arm in order:
                a = d["arms"].get(arm)
                if a is None:
                    continue
                rows.append((model, label, arm, a["recall"],
                             a.get("recall_on_unknown"), a["retrieval_hit"],
                             a["prompt_tokens"], a["seconds_per_probe"]))
    if not rows:
        return None
    out = ["% GENERATED by scripts/make_tables.py -- do not edit by hand",
           "\\begin{tabular}{lllrrrrr}", "\\toprule",
           "model & index & arm & recall & on unknown & answer in "
           "context & tokens/probe & s/probe \\\\", "\\midrule"]
    for model, label, arm, rec, unk, hit, ntok, sec in rows:
        out.append(f"{model} & {label} & {arm} & {100 * rec:.1f}\\% & "
                   + ("--" if unk is None else f"{100 * unk:.1f}\\%")
                   + f" & {100 * hit:.1f}\\% & {ntok:.0f} & {sec:.3f} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out)


def capacity_bits_table():
    """What sets the stored information: rank, cell width, exposures, size.
    Bits are the excess over the released model's priors (eval_bits.py);
    recall is the exact-match figure from the same run for reference."""
    specs = [("3{,}000", "r16", "cap3000_r16"), ("3{,}000", "r64 (s1)", "cap3000_r64_s1"),
             ("3{,}000", "r256", "cap3000_r256"),
             ("10{,}000", "r16", "cap10000_r16"), ("10{,}000", "r32", "cap10000_r32"),
             ("10{,}000", "r64 (s1)", "cap10000_r64_s1"),
             ("10{,}000", "r128", "cap10000_r128"), ("10{,}000", "r256", "cap10000_r256"),
             ("10{,}000", "r64, width 1/2", "cap10000_w5"),
             ("10{,}000", "r64, width 1/4", "cap10000_w25"),
             ("10{,}000", "r64, hardtanh-STE", "cap10000_hardtanh_fill"),
             ("10{,}000", "r64, tanh floor 0.05", "cap10000_tanh_floor"),
             ("10{,}000", "r64, softsign", "cap10000_softsign"),
             ("10{,}000", "r64, $s{=}10$", "cap10000_s10"),
             ("10{,}000", "r64, $s{=}4$", "cap10000_s4_r64"),
             ("10{,}000", "r32, $s{=}10$", "cap10000_s10_r32"),
             ("10{,}000", "r32, $s{=}10$, 4 paraphrases $\\times$ 6 epochs", "cap10000_s10_r32_par4"),
             ("30{,}000", "r32, $s{=}10$", "cap30000_s10_r32"),
             ("10{,}000", "r64, 48 epochs", "cap10000_ep48"),
             ("10{,}000", "r64, 4 paraphrases $\\times$ 6 epochs", "cap10000_aug4_ep6"),
             ("10{,}000", "r64, 4 paraphrases $\\times$ 24 epochs", "cap10000_aug4_ep24"),
             ("10{,}000", "r64, Qwen3-4B", "cap10000_4b"),
             ("30{,}000", "r64", "cap30000_r64"), ("30{,}000", "r256", "cap30000_r256")]
    rows = []
    for n, label, stem in specs:
        b = load(f"bits_{stem}")
        r = (load(f"exp77_{stem}") or load(f"exp79_{stem}")
             or load(f"exp73_cellfill_{stem.split('_')[0][3:]}"))
        if b is None:
            continue
        rec = r["recall"]["merged"] if r else None
        sat = r["merge"]["saturation"] if r else None
        rows.append((n, label, b["excess_bits_per_fact"], b["prior_bits_per_fact"],
                     b["stored_bits_total"], b["bits_per_trainable_param"],
                     b["bits_per_cell"], rec, sat, b["n_trainable"]))
    if not rows:
        return None
    out = ["% GENERATED by scripts/make_tables.py -- do not edit by hand",
           "\\begin{tabular}{llrrrrrr}", "\\toprule",
           "facts & fill & bits/fact & total bits & bits/param & "
           "bits/cell & recall & saturation \\\\", "\\midrule"]
    for n, label, bpf, prior, tot, bpp, bpc, rec, sat, ntr in rows:
        out.append(f"{n} & {label} & {bpf:.2f} of {prior:.1f} & {tot:.2e} & "
                   f"{bpp:.4f} & {bpc:.1e} & "
                   + ("--" if rec is None else f"{100 * rec:.1f}\\%") + " & "
                   + ("--" if sat is None else f"{100 * sat:.1f}\\%") + " \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out)


def capacity_cellfill_table():
    pts = [("1{,}000", ["exp10_qil_r64_qwen3-1.7b", "exp30_qil_r64_s1",
                        "exp30_qil_r64_s2"]),
           ("3{,}000", ["exp73_cellfill_3000"]),
           ("10{,}000", ["exp52_cellfill_10k"]),
           ("30{,}000", ["exp73_cellfill_30000"]),
           ("100{,}000", ["exp53_cellfill_100k"])]
    rows = []
    for label, stems in pts:
        ds = [d for d in (load(s) for s in stems) if d]
        if not ds:
            continue
        n = ds[0]["config"]["n_facts"]
        rec = [d["recall"]["merged"] for d in ds]
        absorbed = [r * n for r in rec]
        lam = [d["ppl_lambada"]["merged"] / d["ppl_lambada"]["anchor_fp32"]
               for d in ds if d.get("ppl_lambada", {}).get("anchor_fp32")]
        rows.append((label, rec, absorbed, lam, [d["merge"]["saturation"] for d in ds],
                     [d["minutes"] for d in ds]))
    if len(rows) < 2:
        return None
    out = ["% GENERATED by scripts/make_tables.py -- do not edit by hand",
           "\\begin{tabular}{lrrrrr}", "\\toprule",
           "facts & recall & absorbed & LAMBADA ratio & saturation & min \\\\",
           "\\midrule"]
    for label, rec, absorbed, lam, sat, mins in rows:
        m, sd, k = agg(rec)
        out.append(f"{label} & {fmt(m, sd, k, pct=True, nd=1)} & "
                   f"{st.mean(absorbed):,.0f} & "
                   + (f"{st.mean(lam):.2f}" if lam else "--")
                   + f" & {100 * st.mean(sat):.2f}\\% & {st.mean(mins):.0f} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out)


if __name__ == "__main__":
    main()
